# Generated by Django 4.2 on 2023-04-14 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0010_remove_news_content_postcontent_newscontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='content_app.category'),
        ),
    ]
