# Generated by Django 4.2 on 2023-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0013_alter_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='robots',
            field=models.CharField(blank=True, default='index, follow', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='robots',
            field=models.CharField(blank=True, default='index, follow', max_length=255, null=True),
        ),
    ]
