# Generated by Django 4.2 on 2023-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0015_rename_preview_image_news_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
