# Generated by Django 4.2 on 2023-04-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_chapter_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_file_topic', to='forum_app.topic'),
        ),
    ]
