# Generated by Django 4.2 on 2023-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('robots', models.CharField(blank=True, default='index, follow', max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='seo/')),
            ],
        ),
    ]
