# Generated by Django 4.2 on 2023-04-20 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.CharField(default='anonymus', max_length=255)),
                ('ip', models.CharField(default='0.0.0.0', max_length=255)),
                ('country', models.CharField(default='unknown', max_length=255)),
                ('isp', models.CharField(default='unknown', max_length=255)),
            ],
        ),
    ]
